defmodule HandbeamWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :handbeam

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_handbeam_key",
    signing_salt: "+8gbeAOy",
    same_site: "Lax"
  ]

  socket "/live", HandbeamWeb.LiveSocket,
    websocket: [connect_info: [:peer_data, :uri, session: @session_options]],
    longpoll: [connect_info: [:peer_data, :uri, session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: {Handbeam.Paths, :static_root, []},
    gzip: not code_reloading?,
    only: HandbeamWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  if code_reloading? do
    socket "/phoenix/live_reload/socket", HandbeamWeb.LiveReloaderSocket,
      websocket: [connect_info: [:peer_data, :uri, session: @session_options]]

    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :handbeam
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  # Endpoint-level so controllers and non-router transports cannot accidentally
  # acquire an unprotected HTTP path. LiveSocket repeats the boundary because
  # Phoenix dispatches socket transports independently of the router pipeline.
  plug HandbeamWeb.Access
  plug HandbeamWeb.Router
end
